# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SOSim2.0.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SOSimMainWindow(object):
    def setupUi(self, SOSimMainWindow):
        SOSimMainWindow.setObjectName(_fromUtf8("SOSimMainWindow"))
        SOSimMainWindow.setEnabled(True)
        SOSimMainWindow.resize(1119, 820)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SOSimMainWindow.sizePolicy().hasHeightForWidth())
        SOSimMainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../Program Files/SOSim/Icons/SOMangel_Icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SOSimMainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(SOSimMainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 341, 221))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gridLayoutWidget.setFont(font)
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.LayoutSpillLocation = QtGui.QGridLayout(self.gridLayoutWidget)
        self.LayoutSpillLocation.setObjectName(_fromUtf8("LayoutSpillLocation"))
        self.SpillLocationGroup = QtGui.QGroupBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SpillLocationGroup.setFont(font)
        self.SpillLocationGroup.setStyleSheet(_fromUtf8(";"))
        self.SpillLocationGroup.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SpillLocationGroup.setObjectName(_fromUtf8("SpillLocationGroup"))
        self.LongSpillLabel = QtGui.QLabel(self.SpillLocationGroup)
        self.LongSpillLabel.setGeometry(QtCore.QRect(10, 160, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LongSpillLabel.setFont(font)
        self.LongSpillLabel.setObjectName(_fromUtf8("LongSpillLabel"))
        self.LatSpillLabel = QtGui.QLabel(self.SpillLocationGroup)
        self.LatSpillLabel.setGeometry(QtCore.QRect(10, 180, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LatSpillLabel.setFont(font)
        self.LatSpillLabel.setObjectName(_fromUtf8("LatSpillLabel"))
        self.LongSpillEdit = QtGui.QLineEdit(self.SpillLocationGroup)
        self.LongSpillEdit.setGeometry(QtCore.QRect(80, 160, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LongSpillEdit.setFont(font)
        self.LongSpillEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.LongSpillEdit.setText(_fromUtf8(""))
        self.LongSpillEdit.setObjectName(_fromUtf8("LongSpillEdit"))
        self.LatSpillEdit = QtGui.QLineEdit(self.SpillLocationGroup)
        self.LatSpillEdit.setGeometry(QtCore.QRect(80, 180, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LatSpillEdit.setFont(font)
        self.LatSpillEdit.setObjectName(_fromUtf8("LatSpillEdit"))
        self.EWSpillBox = QtGui.QGroupBox(self.SpillLocationGroup)
        self.EWSpillBox.setGeometry(QtCore.QRect(170, 160, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.EWSpillBox.setFont(font)
        self.EWSpillBox.setTitle(_fromUtf8(""))
        self.EWSpillBox.setObjectName(_fromUtf8("EWSpillBox"))
        self.SpillE = QtGui.QRadioButton(self.EWSpillBox)
        self.SpillE.setGeometry(QtCore.QRect(10, 0, 41, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SpillE.setFont(font)
        self.SpillE.setObjectName(_fromUtf8("SpillE"))
        self.SpillW = QtGui.QRadioButton(self.EWSpillBox)
        self.SpillW.setGeometry(QtCore.QRect(70, 0, 41, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SpillW.setFont(font)
        self.SpillW.setObjectName(_fromUtf8("SpillW"))
        self.NSSpillgroupBox = QtGui.QGroupBox(self.SpillLocationGroup)
        self.NSSpillgroupBox.setGeometry(QtCore.QRect(170, 180, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.NSSpillgroupBox.setFont(font)
        self.NSSpillgroupBox.setTitle(_fromUtf8(""))
        self.NSSpillgroupBox.setObjectName(_fromUtf8("NSSpillgroupBox"))
        self.SpillN = QtGui.QRadioButton(self.NSSpillgroupBox)
        self.SpillN.setGeometry(QtCore.QRect(10, 0, 41, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SpillN.setFont(font)
        self.SpillN.setObjectName(_fromUtf8("SpillN"))
        self.SpillS = QtGui.QRadioButton(self.NSSpillgroupBox)
        self.SpillS.setGeometry(QtCore.QRect(70, 0, 41, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SpillS.setFont(font)
        self.SpillS.setObjectName(_fromUtf8("SpillS"))
        self.SpillNameLabel = QtGui.QLabel(self.SpillLocationGroup)
        self.SpillNameLabel.setGeometry(QtCore.QRect(10, 20, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SpillNameLabel.setFont(font)
        self.SpillNameLabel.setObjectName(_fromUtf8("SpillNameLabel"))
        self.SpillNameEdit = QtGui.QLineEdit(self.SpillLocationGroup)
        self.SpillNameEdit.setGeometry(QtCore.QRect(80, 20, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SpillNameEdit.setFont(font)
        self.SpillNameEdit.setStatusTip(_fromUtf8(""))
        self.SpillNameEdit.setAutoFillBackground(False)
        self.SpillNameEdit.setFrame(True)
        self.SpillNameEdit.setObjectName(_fromUtf8("SpillNameEdit"))
        self.OilTypeSpinBox = QtGui.QSpinBox(self.SpillLocationGroup)
        self.OilTypeSpinBox.setGeometry(QtCore.QRect(260, 20, 41, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.OilTypeSpinBox.setFont(font)
        self.OilTypeSpinBox.setMinimum(1)
        self.OilTypeSpinBox.setMaximum(5)
        self.OilTypeSpinBox.setProperty("value", 5)
        self.OilTypeSpinBox.setObjectName(_fromUtf8("OilTypeSpinBox"))
        self.label_3 = QtGui.QLabel(self.SpillLocationGroup)
        self.label_3.setGeometry(QtCore.QRect(200, 20, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.TypeofSpill_Lable = QtGui.QLabel(self.SpillLocationGroup)
        self.TypeofSpill_Lable.setGeometry(QtCore.QRect(10, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TypeofSpill_Lable.setFont(font)
        self.TypeofSpill_Lable.setObjectName(_fromUtf8("TypeofSpill_Lable"))
        self.TypeofRelease_Lable = QtGui.QLabel(self.SpillLocationGroup)
        self.TypeofRelease_Lable.setGeometry(QtCore.QRect(10, 60, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TypeofRelease_Lable.setFont(font)
        self.TypeofRelease_Lable.setObjectName(_fromUtf8("TypeofRelease_Lable"))
        self.OilofConcern_Lable = QtGui.QLabel(self.SpillLocationGroup)
        self.OilofConcern_Lable.setGeometry(QtCore.QRect(10, 120, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.OilofConcern_Lable.setFont(font)
        self.OilofConcern_Lable.setObjectName(_fromUtf8("OilofConcern_Lable"))
        self.TypeofSpillBox = QtGui.QGroupBox(self.SpillLocationGroup)
        self.TypeofSpillBox.setGeometry(QtCore.QRect(100, 40, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TypeofSpillBox.setFont(font)
        self.TypeofSpillBox.setTitle(_fromUtf8(""))
        self.TypeofSpillBox.setObjectName(_fromUtf8("TypeofSpillBox"))
        self.well_blowout = QtGui.QRadioButton(self.TypeofSpillBox)
        self.well_blowout.setGeometry(QtCore.QRect(0, 0, 91, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.well_blowout.setFont(font)
        self.well_blowout.setObjectName(_fromUtf8("well_blowout"))
        self.vesselrelease = QtGui.QRadioButton(self.TypeofSpillBox)
        self.vesselrelease.setGeometry(QtCore.QRect(100, 0, 101, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.vesselrelease.setFont(font)
        self.vesselrelease.setObjectName(_fromUtf8("vesselrelease"))
        self.TypeofReleaseBox = QtGui.QGroupBox(self.SpillLocationGroup)
        self.TypeofReleaseBox.setGeometry(QtCore.QRect(100, 60, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TypeofReleaseBox.setFont(font)
        self.TypeofReleaseBox.setTitle(_fromUtf8(""))
        self.TypeofReleaseBox.setObjectName(_fromUtf8("TypeofReleaseBox"))
        self.instantaneous = QtGui.QRadioButton(self.TypeofReleaseBox)
        self.instantaneous.setGeometry(QtCore.QRect(0, 0, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.instantaneous.setFont(font)
        self.instantaneous.setObjectName(_fromUtf8("instantaneous"))
        self.continuous = QtGui.QRadioButton(self.TypeofReleaseBox)
        self.continuous.setGeometry(QtCore.QRect(100, 0, 91, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.continuous.setFont(font)
        self.continuous.setObjectName(_fromUtf8("continuous"))
        self.OilofConcernBox = QtGui.QGroupBox(self.SpillLocationGroup)
        self.OilofConcernBox.setGeometry(QtCore.QRect(110, 120, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.OilofConcernBox.setFont(font)
        self.OilofConcernBox.setTitle(_fromUtf8(""))
        self.OilofConcernBox.setObjectName(_fromUtf8("OilofConcernBox"))
        self.submerged = QtGui.QRadioButton(self.OilofConcernBox)
        self.submerged.setGeometry(QtCore.QRect(0, 0, 91, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.submerged.setFont(font)
        self.submerged.setObjectName(_fromUtf8("submerged"))
        self.sunken = QtGui.QRadioButton(self.OilofConcernBox)
        self.sunken.setGeometry(QtCore.QRect(90, 0, 91, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sunken.setFont(font)
        self.sunken.setObjectName(_fromUtf8("sunken"))
        self.SpillStart_Lable = QtGui.QLabel(self.SpillLocationGroup)
        self.SpillStart_Lable.setGeometry(QtCore.QRect(20, 80, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SpillStart_Lable.setFont(font)
        self.SpillStart_Lable.setObjectName(_fromUtf8("SpillStart_Lable"))
        self.SpillStartHourEdit = QtGui.QTimeEdit(self.SpillLocationGroup)
        self.SpillStartHourEdit.setGeometry(QtCore.QRect(90, 80, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SpillStartHourEdit.setFont(font)
        self.SpillStartHourEdit.setMaximumTime(QtCore.QTime(23, 59, 59))
        self.SpillStartHourEdit.setMinimumTime(QtCore.QTime(0, 0, 0))
        self.SpillStartHourEdit.setCalendarPopup(False)
        self.SpillStartHourEdit.setCurrentSectionIndex(0)
        self.SpillStartHourEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.SpillStartHourEdit.setObjectName(_fromUtf8("SpillStartHourEdit"))
        self.SpillStartDateEdit = QtGui.QDateEdit(self.SpillLocationGroup)
        self.SpillStartDateEdit.setGeometry(QtCore.QRect(170, 80, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SpillStartDateEdit.setFont(font)
        self.SpillStartDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2000,01,01), QtCore.QTime(0, 0, 0)))
        self.SpillStartDateEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2099, 12, 31), QtCore.QTime(23, 59, 59)))
        self.SpillStartDateEdit.setMinimumDate(QtCore.QDate(1900, 1, 1))
        self.SpillStartDateEdit.setMaximumTime(QtCore.QTime(23, 59, 59))
        self.SpillStartDateEdit.setCalendarPopup(True)
        self.SpillStartDateEdit.setObjectName(_fromUtf8("SpillStartDateEdit"))
        self.SpillEnd_Lable = QtGui.QLabel(self.SpillLocationGroup)
        self.SpillEnd_Lable.setGeometry(QtCore.QRect(20, 100, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SpillEnd_Lable.setFont(font)
        self.SpillEnd_Lable.setObjectName(_fromUtf8("SpillEnd_Lable"))
        self.SpillEndHourEdit = QtGui.QTimeEdit(self.SpillLocationGroup)
        self.SpillEndHourEdit.setGeometry(QtCore.QRect(90, 100, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SpillEndHourEdit.setFont(font)
        self.SpillEndHourEdit.setMaximumTime(QtCore.QTime(23, 59, 59))
        self.SpillEndHourEdit.setMinimumTime(QtCore.QTime(0, 0, 0))
        self.SpillEndHourEdit.setCalendarPopup(False)
        self.SpillEndHourEdit.setCurrentSectionIndex(0)
        self.SpillEndHourEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.SpillEndHourEdit.setObjectName(_fromUtf8("SpillEndHourEdit"))
        self.SpillEndDateEdit = QtGui.QDateEdit(self.SpillLocationGroup)
        self.SpillEndDateEdit.setGeometry(QtCore.QRect(170, 100, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SpillEndDateEdit.setFont(font)
        self.SpillEndDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 01, 01), QtCore.QTime(0, 0, 0)))
        self.SpillEndDateEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2099, 12, 31), QtCore.QTime(23, 59, 59)))
        self.SpillEndDateEdit.setMinimumDate(QtCore.QDate(1900, 1, 1))
        self.SpillEndDateEdit.setMaximumTime(QtCore.QTime(23, 59, 59))
        self.SpillEndDateEdit.setCalendarPopup(True)
        self.SpillEndDateEdit.setObjectName(_fromUtf8("SpillEndDateEdit"))
        self.SunkenChooseBox = QtGui.QGroupBox(self.SpillLocationGroup)
        self.SunkenChooseBox.setGeometry(QtCore.QRect(90, 140, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SunkenChooseBox.setFont(font)
        self.SunkenChooseBox.setTitle(_fromUtf8(""))
        self.SunkenChooseBox.setObjectName(_fromUtf8("SunkenChooseBox"))
        self.RiverSpill = QtGui.QRadioButton(self.SunkenChooseBox)
        self.RiverSpill.setGeometry(QtCore.QRect(20, 0, 91, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RiverSpill.setFont(font)
        self.RiverSpill.setObjectName(_fromUtf8("RiverSpill"))
        self.OceanSpill = QtGui.QRadioButton(self.SunkenChooseBox)
        self.OceanSpill.setGeometry(QtCore.QRect(110, 0, 91, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.OceanSpill.setFont(font)
        self.OceanSpill.setObjectName(_fromUtf8("OceanSpill"))
        self.LayoutSpillLocation.addWidget(self.SpillLocationGroup, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 205, 341, 211))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gridLayoutWidget_2.setFont(font)
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.LayoutSamplingProcedure = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.LayoutSamplingProcedure.setObjectName(_fromUtf8("LayoutSamplingProcedure"))
        self.SamplingProcedureGroup = QtGui.QGroupBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SamplingProcedureGroup.setFont(font)
        self.SamplingProcedureGroup.setObjectName(_fromUtf8("SamplingProcedureGroup"))
        self.SampCampaignLabel = QtGui.QLabel(self.SamplingProcedureGroup)
        self.SampCampaignLabel.setGeometry(QtCore.QRect(10, 20, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SampCampaignLabel.setFont(font)
        self.SampCampaignLabel.setObjectName(_fromUtf8("SampCampaignLabel"))
        self.CampaignNumberSpinBox = QtGui.QSpinBox(self.SamplingProcedureGroup)
        self.CampaignNumberSpinBox.setGeometry(QtCore.QRect(200, 20, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CampaignNumberSpinBox.setFont(font)
        self.CampaignNumberSpinBox.setMinimum(1)
        self.CampaignNumberSpinBox.setMaximum(10)
        self.CampaignNumberSpinBox.setObjectName(_fromUtf8("CampaignNumberSpinBox"))
        self.UploadCampaignButton = QtGui.QPushButton(self.SamplingProcedureGroup)
        self.UploadCampaignButton.setGeometry(QtCore.QRect(10, 70, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.UploadCampaignButton.setFont(font)
        self.UploadCampaignButton.setCheckable(False)
        self.UploadCampaignButton.setObjectName(_fromUtf8("UploadCampaignButton"))
        self.RemoveCampaignButton = QtGui.QPushButton(self.SamplingProcedureGroup)
        self.RemoveCampaignButton.setGeometry(QtCore.QRect(230, 70, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RemoveCampaignButton.setFont(font)
        self.RemoveCampaignButton.setObjectName(_fromUtf8("RemoveCampaignButton"))
        self.SampHourEdit = QtGui.QTimeEdit(self.SamplingProcedureGroup)
        self.SampHourEdit.setGeometry(QtCore.QRect(80, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SampHourEdit.setFont(font)
        self.SampHourEdit.setCurrentSection(QtGui.QDateTimeEdit.HourSection)
        self.SampHourEdit.setObjectName(_fromUtf8("SampHourEdit"))
        self.SampDateEdit = QtGui.QDateEdit(self.SamplingProcedureGroup)
        self.SampDateEdit.setGeometry(QtCore.QRect(170, 40, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SampDateEdit.setFont(font)
        self.SampDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 01, 01), QtCore.QTime(0, 0, 0)))
        self.SampDateEdit.setTime(QtCore.QTime(0, 0, 0))
        self.SampDateEdit.setMaximumDate(QtCore.QDate(2099, 12, 31))
        self.SampDateEdit.setMinimumDate(QtCore.QDate(1900, 1, 1))
        self.SampDateEdit.setMinimumTime(QtCore.QTime(0, 0, 0))
        self.SampDateEdit.setCurrentSection(QtGui.QDateTimeEdit.MonthSection)
        self.SampDateEdit.setCalendarPopup(True)
        self.SampDateEdit.setObjectName(_fromUtf8("SampDateEdit"))
        self.SampTimeLabel = QtGui.QLabel(self.SamplingProcedureGroup)
        self.SampTimeLabel.setGeometry(QtCore.QRect(10, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SampTimeLabel.setFont(font)
        self.SampTimeLabel.setObjectName(_fromUtf8("SampTimeLabel"))
        self.OpenCampaignButton = QtGui.QPushButton(self.SamplingProcedureGroup)
        self.OpenCampaignButton.setGeometry(QtCore.QRect(10, 100, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.OpenCampaignButton.setFont(font)
        self.OpenCampaignButton.setObjectName(_fromUtf8("OpenCampaignButton"))
        self.UploadSubmergedHydroButton = QtGui.QPushButton(self.SamplingProcedureGroup)
        self.UploadSubmergedHydroButton.setGeometry(QtCore.QRect(10, 170, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.UploadSubmergedHydroButton.setFont(font)
        self.UploadSubmergedHydroButton.setCheckable(False)
        self.UploadSubmergedHydroButton.setObjectName(_fromUtf8("UploadSubmergedHydroButton"))
        self.HydrodynamicFrame = QtGui.QFrame(self.SamplingProcedureGroup)
        self.HydrodynamicFrame.setGeometry(QtCore.QRect(10, 140, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.HydrodynamicFrame.setFont(font)
        self.HydrodynamicFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.HydrodynamicFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.HydrodynamicFrame.setObjectName(_fromUtf8("HydrodynamicFrame"))
        self.OtherButton = QtGui.QRadioButton(self.HydrodynamicFrame)
        self.OtherButton.setGeometry(QtCore.QRect(140, 0, 61, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.OtherButton.setFont(font)
        self.OtherButton.setObjectName(_fromUtf8("OtherButton"))
        self.NodateButton = QtGui.QRadioButton(self.HydrodynamicFrame)
        self.NodateButton.setGeometry(QtCore.QRect(190, 0, 115, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.NodateButton.setFont(font)
        self.NodateButton.setObjectName(_fromUtf8("NodateButton"))
        self.OSCARButton = QtGui.QRadioButton(self.HydrodynamicFrame)
        self.OSCARButton.setGeometry(QtCore.QRect(10, 0, 61, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.OSCARButton.setFont(font)
        self.OSCARButton.setObjectName(_fromUtf8("OSCARButton"))
        self.GNOMEButton = QtGui.QRadioButton(self.HydrodynamicFrame)
        self.GNOMEButton.setGeometry(QtCore.QRect(70, 0, 61, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.GNOMEButton.setFont(font)
        self.GNOMEButton.setObjectName(_fromUtf8("GNOMEButton"))

        self.UTMButton = QtGui.QRadioButton(self.HydrodynamicFrame)
        self.UTMButton.setGeometry(QtCore.QRect(10, 0, 100, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.UTMButton.setFont(font)
        self.UTMButton.setObjectName(_fromUtf8("UTMButton"))
        self.DecimalButton = QtGui.QRadioButton(self.HydrodynamicFrame)
        self.DecimalButton.setGeometry(QtCore.QRect(110, 0, 100, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DecimalButton.setFont(font)
        self.DecimalButton.setObjectName(_fromUtf8("DecimalButton"))
        self.NodataButton = QtGui.QRadioButton(self.HydrodynamicFrame)
        self.NodataButton.setGeometry(QtCore.QRect(210, 0, 100, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.NodataButton.setFont(font)
        self.NodataButton.setObjectName(_fromUtf8("NodataButton"))

        self.SampCampaignLabel_2 = QtGui.QLabel(self.SamplingProcedureGroup)
        self.SampCampaignLabel_2.setGeometry(QtCore.QRect(10, 120, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SampCampaignLabel_2.setFont(font)
        self.SampCampaignLabel_2.setObjectName(_fromUtf8("SampCampaignLabel_2"))
        self.RemoveSubmergedButton = QtGui.QPushButton(self.SamplingProcedureGroup)
        self.RemoveSubmergedButton.setGeometry(QtCore.QRect(230, 170, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RemoveSubmergedButton.setFont(font)
        self.RemoveSubmergedButton.setObjectName(_fromUtf8("RemoveSubmergedButton"))
        self.LayoutSamplingProcedure.addWidget(self.SamplingProcedureGroup, 0, 0, 1, 1)
        self.gridLayoutWidget_5 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 400, 341, 200))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gridLayoutWidget_5.setFont(font)
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.LayoutAreaGrid = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.LayoutAreaGrid.setObjectName(_fromUtf8("LayoutAreaGrid"))
        self.AreaGridGroup = QtGui.QGroupBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.AreaGridGroup.setFont(font)
        self.AreaGridGroup.setObjectName(_fromUtf8("AreaGridGroup"))

        #Scaleset
        #self.ManSelectAreaButton = QtGui.QPushButton(self.AreaGridGroup)
        self.ScaleBox = QtGui.QGroupBox(self.AreaGridGroup)
        self.ScaleBox.setGeometry(QtCore.QRect(10, 20, 300, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ScaleBox.setFont(font)
        self.ScaleBox.setFlat(True)
        self.ScaleBox.setObjectName(_fromUtf8("ScaleBox"))
        #scale_default button
        self.DefaultScaleRadioButton = QtGui.QRadioButton(self.ScaleBox)
        self.DefaultScaleRadioButton.setGeometry(QtCore.QRect(10,16, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DefaultScaleRadioButton.setFont(font)
        self.DefaultScaleRadioButton.setObjectName(_fromUtf8("DefaultScaleRadioButton"))
        #scale_define button
        self.UserDefinedScaleRadioButton = QtGui.QRadioButton(self.ScaleBox)
        self.UserDefinedScaleRadioButton.setGeometry(QtCore.QRect(10, 40, 84, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.UserDefinedScaleRadioButton.setFont(font)
        self.UserDefinedScaleRadioButton.setObjectName(_fromUtf8("UserDefinedScaleRadioButton"))
        
        self.ScaleFrame = QtGui.QFrame(self.ScaleBox)
        self.ScaleFrame.setGeometry(QtCore.QRect(120, 40, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ScaleFrame.setFont(font)
        self.ScaleFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.ScaleFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.ScaleFrame.setObjectName(_fromUtf8("ScaleFrame"))
        self.latScaleEdit = QtGui.QLineEdit(self.ScaleFrame)
        self.latScaleEdit.setGeometry(QtCore.QRect(130, 0, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.latScaleEdit.setFont(font)
        self.latScaleEdit.setObjectName(_fromUtf8("latScaleEdit"))
        self.ScalelatLabel = QtGui.QLabel(self.ScaleFrame)
        self.ScalelatLabel.setGeometry(QtCore.QRect(90, -1, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ScalelatLabel.setFont(font)
        self.ScalelatLabel.setObjectName(_fromUtf8("ScalelatLabel"))
        self.lonScaleEdit = QtGui.QLineEdit(self.ScaleFrame)
        self.lonScaleEdit.setGeometry(QtCore.QRect(40, 0, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lonScaleEdit.setFont(font)
        self.lonScaleEdit.setObjectName(_fromUtf8("lonScaleEdit"))
        self.ScalelonLabel = QtGui.QLabel(self.ScaleFrame)
        self.ScalelonLabel.setGeometry(QtCore.QRect(0, 0, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ScalelonLabel.setFont(font)
        self.ScalelonLabel.setObjectName(_fromUtf8("ScalelonLabel"))
        self.LayoutAreaGrid.addWidget(self.AreaGridGroup, 0, 0, 1, 1)
        
        self.SureButton = QtGui.QPushButton(self.AreaGridGroup)
        self.SureButton.setGeometry(QtCore.QRect(130, 85, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SureButton.setFont(font)
        self.SureButton.setObjectName(_fromUtf8("SureButton"))
        self.LayoutAreaGrid.addWidget(self.AreaGridGroup, 0, 0, 1, 1)
                
        #NodesBox
        self.groupBox = QtGui.QGroupBox(self.AreaGridGroup)
        self.groupBox.setGeometry(QtCore.QRect(10, 110, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.DefaultNodesRadioButton = QtGui.QRadioButton(self.groupBox)
        self.DefaultNodesRadioButton.setGeometry(QtCore.QRect(10, 16, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DefaultNodesRadioButton.setFont(font)
        self.DefaultNodesRadioButton.setObjectName(_fromUtf8("DefaultNodesRadioButton"))
        self.UserDefinedNodesRadioButton = QtGui.QRadioButton(self.groupBox)
        self.UserDefinedNodesRadioButton.setGeometry(QtCore.QRect(10, 40, 84, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.UserDefinedNodesRadioButton.setFont(font)
        self.UserDefinedNodesRadioButton.setObjectName(_fromUtf8("UserDefinedNodesRadioButton"))
        self.NodesFrame = QtGui.QFrame(self.groupBox)
        self.NodesFrame.setGeometry(QtCore.QRect(120, 40, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.NodesFrame.setFont(font)
        self.NodesFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.NodesFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.NodesFrame.setObjectName(_fromUtf8("NodesFrame"))
        self.yNodesEdit = QtGui.QLineEdit(self.NodesFrame)
        self.yNodesEdit.setGeometry(QtCore.QRect(110, 0, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.yNodesEdit.setFont(font)
        self.yNodesEdit.setObjectName(_fromUtf8("yNodesEdit"))
        self.NodesYLabel = QtGui.QLabel(self.NodesFrame)
        self.NodesYLabel.setGeometry(QtCore.QRect(80, -1, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.NodesYLabel.setFont(font)
        self.NodesYLabel.setObjectName(_fromUtf8("NodesYLabel"))
        self.xNodesEdit = QtGui.QLineEdit(self.NodesFrame)
        self.xNodesEdit.setGeometry(QtCore.QRect(30, 0, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.xNodesEdit.setFont(font)
        self.xNodesEdit.setObjectName(_fromUtf8("xNodesEdit"))
        self.EodesXLabel = QtGui.QLabel(self.NodesFrame)
        self.EodesXLabel.setGeometry(QtCore.QRect(0, 0, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.EodesXLabel.setFont(font)
        self.EodesXLabel.setObjectName(_fromUtf8("EodesXLabel"))
                        
        self.LayoutAreaGrid.addWidget(self.AreaGridGroup, 0, 0, 1, 1)
        self.gridLayoutWidget_6 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 590, 341, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gridLayoutWidget_6.setFont(font)
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.LayoutCalcTimes = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.LayoutCalcTimes.setObjectName(_fromUtf8("LayoutCalcTimes"))
        self.CalcTimesGroup = QtGui.QGroupBox(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CalcTimesGroup.setFont(font)
        self.CalcTimesGroup.setObjectName(_fromUtf8("CalcTimesGroup"))
        self.CalcTimeNumberLabel = QtGui.QLabel(self.CalcTimesGroup)
        self.CalcTimeNumberLabel.setGeometry(QtCore.QRect(10, 21, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CalcTimeNumberLabel.setFont(font)
        self.CalcTimeNumberLabel.setObjectName(_fromUtf8("CalcTimeNumberLabel"))
        self.CalcTimeNumberSpinBox = QtGui.QSpinBox(self.CalcTimesGroup)
        self.CalcTimeNumberSpinBox.setGeometry(QtCore.QRect(140, 20, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CalcTimeNumberSpinBox.setFont(font)
        self.CalcTimeNumberSpinBox.setMinimum(1)
        self.CalcTimeNumberSpinBox.setMaximum(5)
        self.CalcTimeNumberSpinBox.setObjectName(_fromUtf8("CalcTimeNumberSpinBox"))
        self.AddCalcTimeButton = QtGui.QPushButton(self.CalcTimesGroup)
        self.AddCalcTimeButton.setEnabled(True)
        self.AddCalcTimeButton.setGeometry(QtCore.QRect(240, 20, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.AddCalcTimeButton.setFont(font)
        self.AddCalcTimeButton.setObjectName(_fromUtf8("AddCalcTimeButton"))
        self.RemoveCalcTimeButton = QtGui.QPushButton(self.CalcTimesGroup)
        self.RemoveCalcTimeButton.setEnabled(True)
        self.RemoveCalcTimeButton.setGeometry(QtCore.QRect(240, 50, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RemoveCalcTimeButton.setFont(font)
        self.RemoveCalcTimeButton.setObjectName(_fromUtf8("RemoveCalcTimeButton"))
        self.CalcHourEdit = QtGui.QTimeEdit(self.CalcTimesGroup)
        self.CalcHourEdit.setGeometry(QtCore.QRect(40, 50, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CalcHourEdit.setFont(font)
        self.CalcHourEdit.setObjectName(_fromUtf8("CalcHourEdit"))
        self.CalcDateEdit = QtGui.QDateEdit(self.CalcTimesGroup)
        self.CalcDateEdit.setGeometry(QtCore.QRect(120, 50, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CalcDateEdit.setFont(font)
        self.CalcDateEdit.setCalendarPopup(True)
        self.CalcDateEdit.setObjectName(_fromUtf8("CalcDateEdit"))
        self.line = QtGui.QFrame(self.CalcTimesGroup)
        self.line.setGeometry(QtCore.QRect(220, 10, 3, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.line.setFont(font)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label = QtGui.QLabel(self.CalcTimesGroup)
        self.label.setGeometry(QtCore.QRect(10, 50, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.LayoutCalcTimes.addWidget(self.CalcTimesGroup, 0, 0, 1, 1)

        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(350, 0, 21, 721))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.horizontalLayoutWidget.setFont(font)
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.DividerLine = QtGui.QFrame(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DividerLine.setFont(font)
        self.DividerLine.setFrameShape(QtGui.QFrame.VLine)
        self.DividerLine.setFrameShadow(QtGui.QFrame.Sunken)
        self.DividerLine.setObjectName(_fromUtf8("DividerLine"))
        self.horizontalLayout.addWidget(self.DividerLine)
        self.gridLayoutWidget_9 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(370, 40, 561, 511))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gridLayoutWidget_9.setFont(font)
        self.gridLayoutWidget_9.setObjectName(_fromUtf8("gridLayoutWidget_9"))
        self.LayoutMap = QtGui.QGridLayout(self.gridLayoutWidget_9)
        self.LayoutMap.setObjectName(_fromUtf8("LayoutMap"))
        self.frame = QtGui.QFrame(self.gridLayoutWidget_9)
        self.frame.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.frame.setFont(font)
        self.frame.setStatusTip(_fromUtf8(""))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(6)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.LayoutMap.addWidget(self.frame, 0, 0, 3, 1)
        self.gridLayoutWidget_8 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(930, 470, 111, 111))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gridLayoutWidget_8.setFont(font)
        self.gridLayoutWidget_8.setObjectName(_fromUtf8("gridLayoutWidget_8"))
        self.LayoutTimeView = QtGui.QGridLayout(self.gridLayoutWidget_8)
        self.LayoutTimeView.setObjectName(_fromUtf8("LayoutTimeView"))
        self.TimeViewGroup = QtGui.QGroupBox(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TimeViewGroup.setFont(font)
        self.TimeViewGroup.setObjectName(_fromUtf8("TimeViewGroup"))
        self.NextTimeButton = QtGui.QPushButton(self.TimeViewGroup)
        self.NextTimeButton.setEnabled(True)
        self.NextTimeButton.setGeometry(QtCore.QRect(20, 60, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.NextTimeButton.setFont(font)
        self.NextTimeButton.setObjectName(_fromUtf8("NextTimeButton"))
        self.PreviousTimeButton = QtGui.QPushButton(self.TimeViewGroup)
        self.PreviousTimeButton.setEnabled(True)
        self.PreviousTimeButton.setGeometry(QtCore.QRect(20, 20, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PreviousTimeButton.setFont(font)
        self.PreviousTimeButton.setObjectName(_fromUtf8("PreviousTimeButton"))
        self.CurrentTimeEdit = QtGui.QLineEdit(self.TimeViewGroup)
        self.CurrentTimeEdit.setGeometry(QtCore.QRect(10, 40, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CurrentTimeEdit.setFont(font)
        self.CurrentTimeEdit.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.CurrentTimeEdit.setAutoFillBackground(True)
        self.CurrentTimeEdit.setStyleSheet(_fromUtf8(""))
        self.CurrentTimeEdit.setFrame(False)
        self.CurrentTimeEdit.setReadOnly(True)
        self.CurrentTimeEdit.setObjectName(_fromUtf8("CurrentTimeEdit"))
        self.LayoutTimeView.addWidget(self.TimeViewGroup, 0, 0, 1, 1)
        self.gridLayoutWidget_10 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(930, 580, 111, 141))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gridLayoutWidget_10.setFont(font)
        self.gridLayoutWidget_10.setObjectName(_fromUtf8("gridLayoutWidget_10"))
        self.LayoutPan = QtGui.QGridLayout(self.gridLayoutWidget_10)
        self.LayoutPan.setContentsMargins(8, 15, 15, -1)
        self.LayoutPan.setObjectName(_fromUtf8("LayoutPan"))
        self.PanGroup = QtGui.QGroupBox(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PanGroup.setFont(font)
        self.PanGroup.setObjectName(_fromUtf8("PanGroup"))
        self.PanE = QtGui.QRadioButton(self.PanGroup)
        self.PanE.setGeometry(QtCore.QRect(60, 50, 31, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PanE.setFont(font)
        self.PanE.setObjectName(_fromUtf8("PanE"))
        self.PanN = QtGui.QRadioButton(self.PanGroup)
        self.PanN.setGeometry(QtCore.QRect(30, 20, 31, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PanN.setFont(font)
        self.PanN.setObjectName(_fromUtf8("PanN"))
        self.PanS = QtGui.QRadioButton(self.PanGroup)
        self.PanS.setGeometry(QtCore.QRect(30, 80, 43, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PanS.setFont(font)
        self.PanS.setObjectName(_fromUtf8("PanS"))
        self.PanW = QtGui.QRadioButton(self.PanGroup)
        self.PanW.setGeometry(QtCore.QRect(0, 50, 41, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PanW.setFont(font)
        self.PanW.setObjectName(_fromUtf8("PanW"))
        # new center
        self.PanC = QtGui.QRadioButton(self.PanGroup)
        self.PanC.setGeometry(QtCore.QRect(30, 50, 37, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PanC.setFont(font)
        self.PanC.setObjectName(_fromUtf8("PanC"))

        self.LayoutPan.addWidget(self.PanGroup, 0, 0, 1, 1)
        self.gridLayoutWidget_12 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_12.setGeometry(QtCore.QRect(930, 280, 114, 121))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gridLayoutWidget_12.setFont(font)
        self.gridLayoutWidget_12.setObjectName(_fromUtf8("gridLayoutWidget_12"))
        self.LayoutGlobal = QtGui.QGridLayout(self.gridLayoutWidget_12)
        self.LayoutGlobal.setObjectName(_fromUtf8("LayoutGlobal"))
        self.GlobalGroup = QtGui.QGroupBox(self.gridLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.GlobalGroup.setFont(font)
        self.GlobalGroup.setObjectName(_fromUtf8("GlobalGroup"))
        self.frame_2 = QtGui.QFrame(self.GlobalGroup)
        self.frame_2.setGeometry(QtCore.QRect(0, 19, 111, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.LayoutGlobal.addWidget(self.GlobalGroup, 0, 0, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(930, 0, 111, 281))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.verticalLayoutWidget.setFont(font)
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.LayoutLegend = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.LayoutLegend.setContentsMargins(15, 0, 17, 0)
        self.LayoutLegend.setObjectName(_fromUtf8("LayoutLegend"))
        self.groupBox_3 = QtGui.QGroupBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame_3 = QtGui.QFrame(self.groupBox_3)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_2.addWidget(self.frame_3, 0, 0, 1, 1)
        self.LayoutLegend.addWidget(self.groupBox_3)
        self.gridLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(370, 0, 561, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gridLayoutWidget_3.setFont(font)
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_2 = QtGui.QGroupBox(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.TitleEdit = QtGui.QLineEdit(self.groupBox_2)
        self.TitleEdit.setGeometry(QtCore.QRect(0, 0, 591, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TitleEdit.sizePolicy().hasHeightForWidth())
        self.TitleEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.TitleEdit.setFont(font)
        self.TitleEdit.setAutoFillBackground(False)
        self.TitleEdit.setStyleSheet(_fromUtf8("background-color: rgb(213, 209, 206);"))
        self.TitleEdit.setFrame(True)
        self.TitleEdit.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.TitleEdit.setReadOnly(True)
        self.TitleEdit.setObjectName(_fromUtf8("TitleEdit"))
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.gridLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(930, 400, 115, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gridLayoutWidget_4.setFont(font)
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.CoordsLayout = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.CoordsLayout.setObjectName(_fromUtf8("CoordsLayout"))
        self.groupBox_4 = QtGui.QGroupBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit.setGeometry(QtCore.QRect(0, 20, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit.setFont(font)
        self.lineEdit.setAutoFillBackground(True)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.CoordsLayout.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.gridLayoutWidget_14 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_14.setGeometry(QtCore.QRect(370, 540, 561, 171))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gridLayoutWidget_14.setFont(font)
        self.gridLayoutWidget_14.setObjectName(_fromUtf8("gridLayoutWidget_14"))
        self.LayoutBonds_2 = QtGui.QGridLayout(self.gridLayoutWidget_14)
        self.LayoutBonds_2.setObjectName(_fromUtf8("LayoutBonds_2"))
        self.ParameterGroup = QtGui.QGroupBox(self.gridLayoutWidget_14)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ParameterGroup.setFont(font)
        self.ParameterGroup.setObjectName(_fromUtf8("ParameterGroup"))
        self.ParameterBox = QtGui.QGroupBox(self.ParameterGroup)
        self.ParameterBox.setGeometry(QtCore.QRect(10, 20, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ParameterBox.setFont(font)
        self.ParameterBox.setTitle(_fromUtf8(""))
        self.ParameterBox.setObjectName(_fromUtf8("ParameterBox"))
        self.DefaultParameterButton = QtGui.QRadioButton(self.ParameterBox)
        self.DefaultParameterButton.setGeometry(QtCore.QRect(10, 0, 71, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DefaultParameterButton.setFont(font)
        self.DefaultParameterButton.setObjectName(_fromUtf8("DefaultParameterButton"))
        self.UserDefineParameterButton = QtGui.QRadioButton(self.ParameterBox)
        self.UserDefineParameterButton.setGeometry(QtCore.QRect(140, 0, 71, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.UserDefineParameterButton.setFont(font)
        self.UserDefineParameterButton.setObjectName(_fromUtf8("UserDefineParameterButton"))
        self.VXLable = QtGui.QLabel(self.ParameterGroup)
        self.VXLable.setGeometry(QtCore.QRect(21, 41, 22, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.VXLable.setFont(font)
        self.VXLable.setObjectName(_fromUtf8("VXLable"))
        self.VYLabel = QtGui.QLabel(self.ParameterGroup)
        self.VYLabel.setGeometry(QtCore.QRect(156, 41, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.VYLabel.setFont(font)
        self.VYLabel.setObjectName(_fromUtf8("VYLabel"))
        self.DXLabel = QtGui.QLabel(self.ParameterGroup)
        self.DXLabel.setGeometry(QtCore.QRect(21, 61, 22, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DXLabel.setFont(font)
        self.DXLabel.setObjectName(_fromUtf8("DXLabel"))
        self.DYLabel = QtGui.QLabel(self.ParameterGroup)
        self.DYLabel.setGeometry(QtCore.QRect(155, 61, 22, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DYLabel.setFont(font)
        self.DYLabel.setObjectName(_fromUtf8("DYLabel"))
        self.vxMinSpinBox = QtGui.QLineEdit(self.ParameterGroup)
        self.vxMinSpinBox.setGeometry(QtCore.QRect(51, 41, 42, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.vxMinSpinBox.setFont(font)
        self.vxMinSpinBox.setStatusTip(_fromUtf8(""))
        self.vxMinSpinBox.setObjectName(_fromUtf8("vxMinSpinBox"))
        self.vxMaxSpinBox = QtGui.QLineEdit(self.ParameterGroup)
        self.vxMaxSpinBox.setGeometry(QtCore.QRect(103, 41, 43, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.vxMaxSpinBox.setFont(font)
        self.vxMaxSpinBox.setObjectName(_fromUtf8("vxMaxSpinBox"))
        self.DxMinSpinBox = QtGui.QLineEdit(self.ParameterGroup)
        self.DxMinSpinBox.setGeometry(QtCore.QRect(51, 61, 42, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DxMinSpinBox.setFont(font)
        self.DxMinSpinBox.setObjectName(_fromUtf8("DxMinSpinBox"))
        self.DxMaxSpinBox = QtGui.QLineEdit(self.ParameterGroup)
        self.DxMaxSpinBox.setGeometry(QtCore.QRect(103, 61, 42, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DxMaxSpinBox.setFont(font)
        self.DxMaxSpinBox.setObjectName(_fromUtf8("DxMaxSpinBox"))
        self.vyMinSpinBox = QtGui.QLineEdit(self.ParameterGroup)
        self.vyMinSpinBox.setGeometry(QtCore.QRect(185, 41, 42, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.vyMinSpinBox.setFont(font)
        self.vyMinSpinBox.setObjectName(_fromUtf8("vyMinSpinBox"))
        self.vyMaxSpinBox = QtGui.QLineEdit(self.ParameterGroup)
        self.vyMaxSpinBox.setGeometry(QtCore.QRect(237, 41, 43, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.vyMaxSpinBox.setFont(font)
        self.vyMaxSpinBox.setObjectName(_fromUtf8("vyMaxSpinBox"))
        self.DyMinSpinBox = QtGui.QLineEdit(self.ParameterGroup)
        self.DyMinSpinBox.setGeometry(QtCore.QRect(185, 61, 43, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DyMinSpinBox.setFont(font)
        self.DyMinSpinBox.setObjectName(_fromUtf8("DyMinSpinBox"))
        self.DyMaxSpinBox = QtGui.QLineEdit(self.ParameterGroup)
        self.DyMaxSpinBox.setGeometry(QtCore.QRect(238, 61, 42, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DyMaxSpinBox.setFont(font)
        self.DyMaxSpinBox.setObjectName(_fromUtf8("DyMaxSpinBox"))

        self.gridLayoutWidget_7 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 670, 341, 120))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gridLayoutWidget_7.setFont(font)
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.LayoutRun = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.LayoutRun.setObjectName(_fromUtf8("LayoutRun"))


        self.LayoutBonds_2.addWidget(self.ParameterGroup, 0, 0, 1, 1)

        self.gridLayoutWidget_13 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_13.setGeometry(QtCore.QRect(500, 630, 400, 61))  # calibrating line
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gridLayoutWidget_13.setFont(font)
        self.gridLayoutWidget_13.setObjectName(_fromUtf8("gridLayoutWidget_13"))
        self.LayoutRun = QtGui.QGridLayout(self.gridLayoutWidget_13)
        self.LayoutRun.setObjectName(_fromUtf8("LayoutRun"))               
        self.LayoutProgressBar = QtGui.QGridLayout(self.gridLayoutWidget_13)
        self.LayoutProgressBar.setContentsMargins(0, -1, 0, 0)
        self.LayoutProgressBar.setObjectName(_fromUtf8("LayoutProgressBar"))
        self.ProgressBarGroup = QtGui.QGroupBox(self.gridLayoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ProgressBarGroup.setFont(font)
        self.ProgressBarGroup.setTitle(_fromUtf8(""))
        self.ProgressBarGroup.setObjectName(_fromUtf8("ProgressBarGroup"))
        self.ProgressLabel = QtGui.QLabel(self.ProgressBarGroup)
        self.ProgressLabel.setGeometry(QtCore.QRect(0, 10, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ProgressLabel.setFont(font)
        self.ProgressLabel.setObjectName(_fromUtf8("ProgressLabel"))
        self.progressBar = QtGui.QProgressBar(self.ProgressBarGroup)
        self.progressBar.setGeometry(QtCore.QRect(100, 20, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.CancelButton = QtGui.QPushButton(self.ProgressBarGroup)
        self.CancelButton.setGeometry(QtCore.QRect(450, 0, 81, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CancelButton.setFont(font)
        self.CancelButton.setObjectName(_fromUtf8("CancelButton"))
        self.LayoutProgressBar.addWidget(self.ProgressBarGroup, 0, 0, 1, 1)
        self.RunGroup = QtGui.QGroupBox(self.centralwidget)
        self.RunGroup.setGeometry(QtCore.QRect(470, 600, 339, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RunGroup.setFont(font)
        self.RunGroup.setTitle(_fromUtf8(""))
        self.RunGroup.setObjectName(_fromUtf8("RunGroup"))
        self.CalibrateButton = QtGui.QPushButton(self.RunGroup)
        self.CalibrateButton.setGeometry(QtCore.QRect(9, 0, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CalibrateButton.setFont(font)
        self.CalibrateButton.setObjectName(_fromUtf8("CalibrateButton"))
        self.RunButton = QtGui.QPushButton(self.RunGroup)
        self.RunButton.setGeometry(QtCore.QRect(107, 0, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RunButton.setFont(font)
        self.RunButton.setObjectName(_fromUtf8("RunButton"))
        self.RecalcButton = QtGui.QPushButton(self.RunGroup)
        self.RecalcButton.setGeometry(QtCore.QRect(205, 0, 95, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RecalcButton.setFont(font)
        self.RecalcButton.setObjectName(_fromUtf8("RecalcButton"))
        self.LayoutRun.addWidget(self.RunGroup, 0, 0, 1, 1)
#############################################################
        self.LayoutGlobal.addWidget(self.GlobalGroup, 0, 0, 1, 1)
        self.gridLayoutWidget_18 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_18.setGeometry(QtCore.QRect(370, 660, 561, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gridLayoutWidget_18.setFont(font)
        self.gridLayoutWidget_18.setObjectName(_fromUtf8("gridLayoutWidget_18"))
        self.LayoutProgressBar = QtGui.QGridLayout(self.gridLayoutWidget_18)
        self.LayoutProgressBar.setContentsMargins(0, -1, 0, 0)
        self.LayoutProgressBar.setObjectName(_fromUtf8("LayoutProgressBar"))
        self.ProgressBarGroup = QtGui.QGroupBox(self.gridLayoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ProgressBarGroup.setFont(font)
        self.ProgressBarGroup.setTitle(_fromUtf8(""))
        self.ProgressBarGroup.setObjectName(_fromUtf8("ProgressBarGroup"))
        self.ProgressLabel = QtGui.QLabel(self.ProgressBarGroup)
        self.ProgressLabel.setGeometry(QtCore.QRect(0, 10, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ProgressLabel.setFont(font)
        self.ProgressLabel.setObjectName(_fromUtf8("ProgressLabel"))
        self.progressBar = QtGui.QProgressBar(self.ProgressBarGroup)
        self.progressBar.setGeometry(QtCore.QRect(100, 10, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.CancelButton = QtGui.QPushButton(self.ProgressBarGroup)
        self.CancelButton.setGeometry(QtCore.QRect(450, 10, 81, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CancelButton.setFont(font)
        self.CancelButton.setObjectName(_fromUtf8("CancelButton"))
        self.LayoutProgressBar.addWidget(self.ProgressBarGroup, 0, 0, 1, 1)
###################################################
        self.gridLayoutWidget_7 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 670, 341, 120))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gridLayoutWidget_7.setFont(font)
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.LayoutRun = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.LayoutRun.setObjectName(_fromUtf8("LayoutRun"))
        self.ParameterGroup_3 = QtGui.QGroupBox(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ParameterGroup_3.setFont(font)
        self.ParameterGroup_3.setObjectName(_fromUtf8("ParameterGroup_3"))
        self.ParameterBox_4 = QtGui.QGroupBox(self.ParameterGroup_3)
        self.ParameterBox_4.setGeometry(QtCore.QRect(10, 20, 531, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ParameterBox_4.setFont(font)
        self.ParameterBox_4.setTitle(_fromUtf8(""))
        self.ParameterBox_4.setObjectName(_fromUtf8("ParameterBox_4"))
        self.DefaultParameterButton_6 = QtGui.QRadioButton(self.ParameterBox_4)
        self.DefaultParameterButton_6.setGeometry(QtCore.QRect(10, 0, 101, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DefaultParameterButton_6.setFont(font)
        self.DefaultParameterButton_6.setObjectName(_fromUtf8("DefaultParameterButton_6"))
        self.DefaultParameterButton_7 = QtGui.QRadioButton(self.ParameterBox_4)
        self.DefaultParameterButton_7.setGeometry(QtCore.QRect(120, 0, 161, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DefaultParameterButton_7.setFont(font)
        self.DefaultParameterButton_7.setObjectName(_fromUtf8("DefaultParameterButton_7"))
        self.VXLable_4 = QtGui.QLabel(self.ParameterBox_4)
        self.VXLable_4.setGeometry(QtCore.QRect(20, 20, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.VXLable_4.setFont(font)
        self.VXLable_4.setObjectName(_fromUtf8("VXLable_4"))
        self.vyMinSpinBox_3 = QtGui.QLineEdit(self.ParameterBox_4)
        self.vyMinSpinBox_3.setGeometry(QtCore.QRect(140, 20, 42, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.vyMinSpinBox_3.setFont(font)
        self.vyMinSpinBox_3.setObjectName(_fromUtf8("vyMinSpinBox_3"))
        self.VXLable_5 = QtGui.QLabel(self.ParameterBox_4)
        self.VXLable_5.setGeometry(QtCore.QRect(20, 40, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.VXLable_5.setFont(font)
        self.VXLable_5.setObjectName(_fromUtf8("VXLable_5"))
        self.ParameterBox_7 = QtGui.QGroupBox(self.ParameterBox_4)
        self.ParameterBox_7.setGeometry(QtCore.QRect(120, 40, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ParameterBox_7.setFont(font)
        self.ParameterBox_7.setTitle(_fromUtf8(""))
        self.ParameterBox_7.setObjectName(_fromUtf8("ParameterBox_7"))
        self.DefaultParameterButton_17 = QtGui.QRadioButton(self.ParameterBox_7)
        self.DefaultParameterButton_17.setGeometry(QtCore.QRect(0, 0, 61, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DefaultParameterButton_17.setFont(font)
        self.DefaultParameterButton_17.setObjectName(_fromUtf8("DefaultParameterButton_17"))
        self.DefaultParameterButton_18 = QtGui.QRadioButton(self.ParameterBox_7)
        self.DefaultParameterButton_18.setGeometry(QtCore.QRect(60, 0, 61, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DefaultParameterButton_18.setFont(font)
        self.DefaultParameterButton_18.setObjectName(_fromUtf8("DefaultParameterButton_18"))
        self.DefaultParameterButton_19 = QtGui.QRadioButton(self.ParameterBox_7)
        self.DefaultParameterButton_19.setGeometry(QtCore.QRect(100, 0, 61, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DefaultParameterButton_19.setFont(font)
        self.DefaultParameterButton_19.setObjectName(_fromUtf8("DefaultParameterButton_19"))
        self.LayoutRun.addWidget(self.ParameterGroup_3, 0, 0, 1, 1)
###################################################
        self.Outputoptions = QtGui.QGroupBox(self.centralwidget)
        self.Outputoptions.setGeometry(QtCore.QRect(658, 550, 271, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Outputoptions.setFont(font)
        self.Outputoptions.setObjectName(_fromUtf8("Outputoptions"))
        self.ParameterBox_2 = QtGui.QGroupBox(self.Outputoptions)
        self.ParameterBox_2.setGeometry(QtCore.QRect(10, 20, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ParameterBox_2.setFont(font)
        self.ParameterBox_2.setTitle(_fromUtf8(""))
        self.ParameterBox_2.setObjectName(_fromUtf8("ParameterBox_2"))
        self.CoordinateButton = QtGui.QRadioButton(self.ParameterBox_2)
        self.CoordinateButton.setGeometry(QtCore.QRect(10, 0, 91, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CoordinateButton.setFont(font)
        self.CoordinateButton.setObjectName(_fromUtf8("CoordinateButton"))
        self.KmButton = QtGui.QRadioButton(self.ParameterBox_2)
        self.KmButton.setGeometry(QtCore.QRect(120, 0, 91, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.KmButton.setFont(font)
        self.KmButton.setObjectName(_fromUtf8("KmButton"))
        self.ParameterBox_4 = QtGui.QGroupBox(self.Outputoptions)
        self.ParameterBox_4.setGeometry(QtCore.QRect(10, 40, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ParameterBox_4.setFont(font)
        self.ParameterBox_4.setTitle(_fromUtf8(""))
        self.ParameterBox_4.setObjectName(_fromUtf8("ParameterBox_4"))
        self.ContourButton = QtGui.QRadioButton(self.ParameterBox_4)
        self.ContourButton.setGeometry(QtCore.QRect(10, 0, 71, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ContourButton.setFont(font)
        self.ContourButton.setObjectName(_fromUtf8("ContourButton"))
        self.NocontourButton = QtGui.QRadioButton(self.ParameterBox_4)
        self.NocontourButton.setGeometry(QtCore.QRect(120, 0, 121, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.NocontourButton.setFont(font)
        self.NocontourButton.setObjectName(_fromUtf8("NocontourButton"))
        self.FielddataButton = QtGui.QRadioButton(self.Outputoptions)
        self.FielddataButton.setGeometry(QtCore.QRect(20, 60, 101, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.FielddataButton.setFont(font)
        self.FielddataButton.setObjectName(_fromUtf8("FielddataButton"))
        self.NoFielddataButton = QtGui.QRadioButton(self.Outputoptions)
        self.NoFielddataButton.setGeometry(QtCore.QRect(130, 60, 101, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.NoFielddataButton.setFont(font)
        self.NoFielddataButton.setObjectName(_fromUtf8("NoFielddataButton"))
        self.ParameterBox_2.raise_()
        self.ParameterBox_4.raise_()
        self.ParameterGroup.raise_()
#######################################
        SOSimMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(SOSimMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1119, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)

        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menuPrint = QtGui.QMenu(self.menu_File)
        self.menuPrint.setObjectName(_fromUtf8("menuPrint"))
        self.menuOpen = QtGui.QMenu(self.menu_File)
        self.menuOpen.setObjectName(_fromUtf8("menuOpen"))
        self.menuMap = QtGui.QMenu(self.menubar)
        self.menuMap.setObjectName(_fromUtf8("menuMap"))
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        SOSimMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(SOSimMainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        SOSimMainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(SOSimMainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../Program Files/SOSim/Icons/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(SOSimMainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../Program Files/SOSim/Icons/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(SOSimMainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionSave_Image = QtGui.QAction(SOSimMainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../Program Files/SOSim/Icons/mActionSaveMapAsImage.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_Image.setIcon(icon3)
        self.actionSave_Image.setObjectName(_fromUtf8("actionSave_Image"))
        self.actionQuit = QtGui.QAction(SOSimMainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionCurrent_Image = QtGui.QAction(SOSimMainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../../SOSim2.0/SOSim2.0/Icons/print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCurrent_Image.setIcon(icon4)
        self.actionCurrent_Image.setObjectName(_fromUtf8("actionCurrent_Image"))
        self.actionSpill = QtGui.QAction(SOSimMainWindow)
        self.actionSpill.setObjectName(_fromUtf8("actionSpill"))
        self.actionModeling_area_within_current_spill = QtGui.QAction(SOSimMainWindow)
        self.actionModeling_area_within_current_spill.setObjectName(_fromUtf8("actionModeling_area_within_current_spill"))
        self.actionAddLayer = QtGui.QAction(SOSimMainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../Program Files/SOSim/Icons/mActionAddLayer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddLayer.setIcon(icon5)
        self.actionAddLayer.setObjectName(_fromUtf8("actionAddLayer"))
        self.actionZoomIn = QtGui.QAction(SOSimMainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../Program Files/SOSim/Icons/mActionZoomIn.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomIn.setIcon(icon6)
        self.actionZoomIn.setObjectName(_fromUtf8("actionZoomIn"))
        self.actionZoomOut = QtGui.QAction(SOSimMainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../Program Files/SOSim/Icons/mActionZoomOut.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomOut.setIcon(icon7)
        self.actionZoomOut.setObjectName(_fromUtf8("actionZoomOut"))
        self.actionPan = QtGui.QAction(SOSimMainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../Program Files/SOSim/Icons/mActionPan.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPan.setIcon(icon8)
        self.actionPan.setObjectName(_fromUtf8("actionPan"))
        self.actionNew = QtGui.QAction(SOSimMainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../Program Files/SOSim/Icons/new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon9)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionSelectBoundary = QtGui.QAction(SOSimMainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../Program Files/SOSim/Icons/mSelectBoundary.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelectBoundary.setIcon(icon10)
        self.actionSelectBoundary.setObjectName(_fromUtf8("actionSelectBoundary"))
        self.actionCaptureCoordinates = QtGui.QAction(SOSimMainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../Program Files/SOSim/Icons/mActionCaptureCoordinates.PNG")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCaptureCoordinates.setIcon(icon11)
        self.actionCaptureCoordinates.setObjectName(_fromUtf8("actionCaptureCoordinates"))
        self.actionSave_Calibration_As = QtGui.QAction(SOSimMainWindow)
        self.actionSave_Calibration_As.setObjectName(_fromUtf8("actionSave_Calibration_As"))
        self.actionExisting_Output_Image = QtGui.QAction(SOSimMainWindow)
        self.actionExisting_Output_Image.setObjectName(_fromUtf8("actionExisting_Output_Image"))
        self.actionDefaultSettings = QtGui.QAction(SOSimMainWindow)
        self.actionDefaultSettings.setObjectName(_fromUtf8("actionDefaultSettings"))
        self.actionDefaultGridNodes = QtGui.QAction(SOSimMainWindow)
        self.actionDefaultGridNodes.setObjectName(_fromUtf8("actionDefaultGridNodes"))
        self.actionDefaultResolution = QtGui.QAction(SOSimMainWindow)
        self.actionDefaultResolution.setObjectName(_fromUtf8("actionDefaultResolution"))
        self.menuPrint.addAction(self.actionCurrent_Image)
        self.menuOpen.addAction(self.actionExisting_Output_Image)
        self.menu_File.addAction(self.actionNew)
        self.menu_File.addAction(self.menuOpen.menuAction())
        self.menu_File.addAction(self.actionSave_Calibration_As)
        self.menu_File.addAction(self.actionSave_Image)
        self.menu_File.addAction(self.menuPrint.menuAction())
        self.menu_File.addAction(self.actionQuit)
        self.menuMap.addAction(self.actionAddLayer)
        self.menuMap.addAction(self.actionCaptureCoordinates)
        self.menuMap.addAction(self.actionPan)
        self.menuMap.addAction(self.actionSelectBoundary)
        self.menuMap.addAction(self.actionZoomIn)
        self.menuMap.addAction(self.actionZoomOut)
        self.menuOptions.addAction(self.actionDefaultSettings)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuMap.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.LongSpillLabel.setBuddy(self.LongSpillEdit)
        self.LatSpillLabel.setBuddy(self.LatSpillEdit)
        self.SampCampaignLabel.setBuddy(self.CampaignNumberSpinBox)
        self.SampTimeLabel.setBuddy(self.SampHourEdit)
        self.SampCampaignLabel_2.setBuddy(self.CampaignNumberSpinBox)
        self.CalcTimeNumberLabel.setBuddy(self.CalcTimeNumberSpinBox)
        self.VXLable.setBuddy(self.LongSpillEdit)
        self.VYLabel.setBuddy(self.LongSpillEdit)
        self.DXLabel.setBuddy(self.LongSpillEdit)
        self.DYLabel.setBuddy(self.LongSpillEdit)

        self.retranslateUi(SOSimMainWindow)
        QtCore.QObject.connect(self.instantaneous, QtCore.SIGNAL(_fromUtf8("clicked()")), self.SpillEnd_Lable.hide)
        QtCore.QObject.connect(self.continuous, QtCore.SIGNAL(_fromUtf8("clicked()")), self.SpillEnd_Lable.show)
        QtCore.QObject.connect(self.instantaneous, QtCore.SIGNAL(_fromUtf8("clicked()")), self.SpillEndHourEdit.hide)
        QtCore.QObject.connect(self.instantaneous, QtCore.SIGNAL(_fromUtf8("clicked()")), self.SpillEndDateEdit.hide)
        QtCore.QObject.connect(self.continuous, QtCore.SIGNAL(_fromUtf8("clicked()")), self.SpillEndHourEdit.show)
        QtCore.QObject.connect(self.continuous, QtCore.SIGNAL(_fromUtf8("clicked()")), self.SpillEndDateEdit.show)
        QtCore.QObject.connect(self.DefaultNodesRadioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.EodesXLabel.close)
        QtCore.QObject.connect(self.DefaultNodesRadioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.xNodesEdit.close)
        QtCore.QObject.connect(self.DefaultNodesRadioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.NodesYLabel.close)
        QtCore.QObject.connect(self.UserDefinedNodesRadioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.EodesXLabel.show)
        QtCore.QObject.connect(self.UserDefinedNodesRadioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.xNodesEdit.show)
        QtCore.QObject.connect(self.UserDefinedNodesRadioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.NodesYLabel.show)
        QtCore.QObject.connect(self.UserDefinedNodesRadioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.yNodesEdit.show)
        QtCore.QObject.connect(self.DefaultParameterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.VXLable.hide)
        QtCore.QObject.connect(self.DefaultParameterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.DXLabel.hide)
        QtCore.QObject.connect(self.DefaultParameterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.vxMinSpinBox.hide)
        QtCore.QObject.connect(self.DefaultParameterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.DxMinSpinBox.hide)
        QtCore.QObject.connect(self.DefaultParameterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.vxMaxSpinBox.hide)
        QtCore.QObject.connect(self.DefaultParameterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.DxMaxSpinBox.hide)
        QtCore.QObject.connect(self.DefaultParameterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.VYLabel.hide)
        QtCore.QObject.connect(self.DefaultParameterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.DYLabel.hide)
        QtCore.QObject.connect(self.DefaultParameterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.vyMinSpinBox.hide)
        QtCore.QObject.connect(self.DefaultParameterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.DyMinSpinBox.hide)
        QtCore.QObject.connect(self.DefaultParameterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.vyMaxSpinBox.hide)
        QtCore.QObject.connect(self.DefaultParameterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.DyMaxSpinBox.hide)
        QtCore.QObject.connect(self.UserDefineParameterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.VXLable.show)
        QtCore.QObject.connect(self.UserDefineParameterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.DXLabel.show)
        QtCore.QObject.connect(self.UserDefineParameterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.vxMinSpinBox.show)
        QtCore.QObject.connect(self.UserDefineParameterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.DxMinSpinBox.show)
        QtCore.QObject.connect(self.UserDefineParameterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.vxMaxSpinBox.show)
        QtCore.QObject.connect(self.UserDefineParameterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.DxMaxSpinBox.show)
        QtCore.QObject.connect(self.UserDefineParameterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.VYLabel.show)
        QtCore.QObject.connect(self.UserDefineParameterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.DYLabel.show)
        QtCore.QObject.connect(self.UserDefineParameterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.vyMinSpinBox.show)
        QtCore.QObject.connect(self.UserDefineParameterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.DyMinSpinBox.show)
        QtCore.QObject.connect(self.UserDefineParameterButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.vyMaxSpinBox.show)

        # QtCore.QObject.connect(self.sunken, QtCore.SIGNAL(_fromUtf8("clicked()")), self.OceanSpill.click)
        QtCore.QObject.connect(self.submerged, QtCore.SIGNAL(_fromUtf8("clicked()")), self.RiverSpill.hide)
        QtCore.QObject.connect(self.submerged, QtCore.SIGNAL(_fromUtf8("clicked()")), self.OceanSpill.hide)
        QtCore.QObject.connect(self.DefaultNodesRadioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.yNodesEdit.hide)
        #confidence

        QtCore.QObject.connect(self.DefaultParameterButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), self.VXLable_4.hide)
        QtCore.QObject.connect(self.DefaultParameterButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), self.vyMinSpinBox_3.hide)
        QtCore.QObject.connect(self.DefaultParameterButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), self.VXLable_5.hide)
        QtCore.QObject.connect(self.DefaultParameterButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), self.ParameterBox_7.hide)
        QtCore.QObject.connect(self.DefaultParameterButton_7, QtCore.SIGNAL(_fromUtf8("clicked()")), self.VXLable_4.show)
        QtCore.QObject.connect(self.DefaultParameterButton_7, QtCore.SIGNAL(_fromUtf8("clicked()")), self.vyMinSpinBox_3.show)
        QtCore.QObject.connect(self.DefaultParameterButton_7, QtCore.SIGNAL(_fromUtf8("clicked()")), self.VXLable_5.show)
        QtCore.QObject.connect(self.DefaultParameterButton_7, QtCore.SIGNAL(_fromUtf8("clicked()")), self.ParameterBox_7.show)

        QtCore.QMetaObject.connectSlotsByName(SOSimMainWindow)
        SOSimMainWindow.setTabOrder(self.SpillNameEdit, self.LongSpillEdit)
        SOSimMainWindow.setTabOrder(self.LongSpillEdit, self.SpillE)
        SOSimMainWindow.setTabOrder(self.SpillE, self.SpillW)
        SOSimMainWindow.setTabOrder(self.SpillW, self.LatSpillEdit)
        SOSimMainWindow.setTabOrder(self.LatSpillEdit, self.SpillN)
        SOSimMainWindow.setTabOrder(self.SpillN, self.SpillS)
        SOSimMainWindow.setTabOrder(self.SpillS, self.CampaignNumberSpinBox)
        SOSimMainWindow.setTabOrder(self.CampaignNumberSpinBox, self.SampHourEdit)
        SOSimMainWindow.setTabOrder(self.SampHourEdit, self.SampDateEdit)
        SOSimMainWindow.setTabOrder(self.SampDateEdit, self.UploadCampaignButton)
        SOSimMainWindow.setTabOrder(self.UploadCampaignButton, self.RemoveCampaignButton)
        #SOSimMainWindow.setTabOrder(self.RemoveCampaignButton, self.ManSelectAreaButton)
        #SOSimMainWindow.setTabOrder(self.ManSelectAreaButton, self.AutoSelectAreaButton)
        #SOSimMainWindow.setTabOrder(self.AutoSelectAreaButton, self.DefaultNodesRadioButton)
        SOSimMainWindow.setTabOrder(self.DefaultNodesRadioButton, self.xNodesEdit)
        SOSimMainWindow.setTabOrder(self.xNodesEdit, self.yNodesEdit)
        SOSimMainWindow.setTabOrder(self.yNodesEdit, self.CalcTimeNumberSpinBox)
        SOSimMainWindow.setTabOrder(self.CalcTimeNumberSpinBox, self.CalcHourEdit)
        SOSimMainWindow.setTabOrder(self.CalcHourEdit, self.CalcDateEdit)
        SOSimMainWindow.setTabOrder(self.CalcDateEdit, self.AddCalcTimeButton)
        SOSimMainWindow.setTabOrder(self.AddCalcTimeButton, self.RemoveCalcTimeButton)
        SOSimMainWindow.setTabOrder(self.RemoveCalcTimeButton, self.PreviousTimeButton)
        SOSimMainWindow.setTabOrder(self.PreviousTimeButton, self.NextTimeButton)
        SOSimMainWindow.setTabOrder(self.NextTimeButton, self.PanN)
        SOSimMainWindow.setTabOrder(self.PanN, self.PanS)
        SOSimMainWindow.setTabOrder(self.PanS, self.PanW)
        SOSimMainWindow.setTabOrder(self.PanW, self.PanE)
        SOSimMainWindow.setTabOrder(self.PanE, self.CancelButton)

    def retranslateUi(self, SOSimMainWindow):
        SOSimMainWindow.setWindowTitle(_translate("SOSimMainWindow", "SOSim2.0 - Subsurface Oil Simulator", None))
        self.SpillLocationGroup.setTitle(_translate("SOSimMainWindow", "1.Spill information", None))
        self.LongSpillLabel.setText(_translate("SOSimMainWindow", "Longitude:", None))
        self.LatSpillLabel.setText(_translate("SOSimMainWindow", "Latitude:", None))
        self.LongSpillEdit.setWhatsThis(_translate("SOSimMainWindow", "Enter the Longitude in degrees, with minutes and seconds in decimal form.", None))
        self.SpillE.setText(_translate("SOSimMainWindow", "E", None))
        self.SpillW.setText(_translate("SOSimMainWindow", "W", None))
        self.SpillN.setText(_translate("SOSimMainWindow", "N", None))
        self.SpillS.setText(_translate("SOSimMainWindow", " S", None))
        self.SpillNameLabel.setText(_translate("SOSimMainWindow", "Spill Name:", None))
        self.label_3.setWhatsThis(_translate("SOSimMainWindow", "Oil type: 1 for high API gravities, 6 for low API gravities", None))
        self.label_3.setText(_translate("SOSimMainWindow", "Oil group:", None))
        self.TypeofSpill_Lable.setText(_translate("SOSimMainWindow", "Type of Spill:", None))
        self.TypeofRelease_Lable.setText(_translate("SOSimMainWindow", "Type of Release:", None))
        self.OilofConcern_Lable.setText(_translate("SOSimMainWindow", "Oil of Concern:", None))
        self.well_blowout.setText(_translate("SOSimMainWindow", "well-blowout", None))
        self.vesselrelease.setText(_translate("SOSimMainWindow", "vessel release", None))
        self.instantaneous.setToolTip(_translate("SOSimMainWindow", "the duration of the spill is equal or less than 1 h", None))
        self.instantaneous.setText(_translate("SOSimMainWindow", "instantaneous", None))
        self.continuous.setText(_translate("SOSimMainWindow", "continuous", None))
        self.submerged.setText(_translate("SOSimMainWindow", "submerged", None))
        self.sunken.setText(_translate("SOSimMainWindow", "sunken", None))
        self.SpillStart_Lable.setText(_translate("SOSimMainWindow", "Spill Start:", None))
        self.SpillStartHourEdit.setDisplayFormat(_translate("SOSimMainWindow", "h:mm AP", None))
        self.SpillStartDateEdit.setDisplayFormat(_translate("SOSimMainWindow", "MM/dd/yyyy", None))
        self.SpillEnd_Lable.setText(_translate("SOSimMainWindow", "Spill End:", None))
        self.SpillEndHourEdit.setDisplayFormat(_translate("SOSimMainWindow", "h:mm AP", None))
        self.SpillEndDateEdit.setDisplayFormat(_translate("SOSimMainWindow", "MM/dd/yyyy", None))
        self.RiverSpill.setText(_translate("SOSimMainWindow", "River spill", None))
        self.OceanSpill.setText(_translate("SOSimMainWindow", "Ocean spill", None))
        self.SamplingProcedureGroup.setTitle(_translate("SOSimMainWindow", "2.Sampling campaign(s)", None))
        self.SampCampaignLabel.setText(_translate("SOSimMainWindow", "Sampling Campaign Number:", None))
        self.UploadCampaignButton.setText(_translate("SOSimMainWindow", "Upload Sampling Campaign Data File", None))
        self.RemoveCampaignButton.setText(_translate("SOSimMainWindow", "Remove", None))
        self.SampHourEdit.setDisplayFormat(_translate("SOSimMainWindow", "h:mm AP", None))
        self.SampDateEdit.setDisplayFormat(_translate("SOSimMainWindow", "MM/dd/yyyy", None))
        self.SampTimeLabel.setText(_translate("SOSimMainWindow", "Started at", None))
        self.OpenCampaignButton.setText(_translate("SOSimMainWindow", "Use Existing Calibration File...", None))
        self.UploadSubmergedHydroButton.setText(_translate("SOSimMainWindow", "Submerged Hydrodynamic Upload", None))
        self.OtherButton.setText(_translate("SOSimMainWindow", "Other", None))
        self.NodateButton.setText(_translate("SOSimMainWindow", "No Model Data", None))
        self.OSCARButton.setText(_translate("SOSimMainWindow", "OSCAR", None))
        self.GNOMEButton.setText(_translate("SOSimMainWindow", "GNOME", None))
        self.NodataButton.setText(_translate("SOSimMainWindow", "No Model Data", None))
        self.UTMButton.setText(_translate("SOSimMainWindow", "UTM coord", None))
        self.DecimalButton.setText(_translate("SOSimMainWindow", "Decimal degrees", None))
        self.VXLable_4.setText(_translate("SOSimMainWindow", "Level of Confidence:", None))
        self.vyMinSpinBox_3.setToolTip(_translate("SOSimMainWindow", "Level of Confidence", None))
        self.ParameterGroup_3.setTitle(_translate("SOSimMainWindow", "5.Uncertainty Estimates", None))
        self.DefaultParameterButton_6.setText(_translate("SOSimMainWindow", "Best Guess", None))
        self.DefaultParameterButton_7.setText(_translate("SOSimMainWindow", "Minimum Regret:", None))
        self.VXLable_5.setText(_translate("SOSimMainWindow", "Threshold Concentration", None))
        self.DefaultParameterButton_17.setText(_translate("SOSimMainWindow", "0.1%", None))
        self.DefaultParameterButton_18.setText(_translate("SOSimMainWindow", "1%", None))
        self.DefaultParameterButton_19.setText(_translate("SOSimMainWindow", "10%", None))               
        self.SampCampaignLabel_2.setText(_translate("SOSimMainWindow", "Submerged Hydrodynamic campaign(s)", None))
        self.RemoveSubmergedButton.setText(_translate("SOSimMainWindow", "Remove", None))
        self.AreaGridGroup.setTitle(_translate("SOSimMainWindow", "3.Modeling Area and Grid", None))
        #self.ManSelectAreaButton.setText(_translate("SOSimMainWindow", "Select Area from Map", None))
        #self.AutoSelectAreaButton.setText(_translate("SOSimMainWindow", "Auto Select Area", None))
        #Scale
        self.ScaleBox.setTitle(_translate("SOSimMainWindow", "Scale:", None))
        self.DefaultScaleRadioButton.setText(_translate("SOSimMainWindow", "Default", None))
        self.UserDefinedScaleRadioButton.setText(_translate("SOSimMainWindow", "Define...", None))
        self.ScalelatLabel.setText(_translate("SOSimMainWindow", "lat_(km):", None))
        self.ScalelonLabel.setText(_translate("SOSimMainWindow", "lon_(km):", None))
        self.SureButton.setText(_translate("SOSimMainWindow", "Sure", None))
        #Node
        self.groupBox.setTitle(_translate("SOSimMainWindow", "Number of Grid Nodes:", None))
        self.DefaultNodesRadioButton.setText(_translate("SOSimMainWindow", "Default", None))
        self.UserDefinedNodesRadioButton.setText(_translate("SOSimMainWindow", "Define...", None))
        self.NodesYLabel.setText(_translate("SOSimMainWindow", "N-S:", None))
        self.EodesXLabel.setText(_translate("SOSimMainWindow", "E-W:", None))
        self.CalcTimesGroup.setTitle(_translate("SOSimMainWindow", "4.Prediction Times", None))
        self.CalcTimeNumberLabel.setText(_translate("SOSimMainWindow", "Prediction Number:", None))
        self.AddCalcTimeButton.setText(_translate("SOSimMainWindow", "Add", None))
        self.RemoveCalcTimeButton.setText(_translate("SOSimMainWindow", "Delete", None))
        self.CalcHourEdit.setDisplayFormat(_translate("SOSimMainWindow", "h:mm AP", None))
        self.CalcDateEdit.setDisplayFormat(_translate("SOSimMainWindow", "MM/dd/yyyy", None))
        self.label.setText(_translate("SOSimMainWindow", "At:", None))
        self.CalibrateButton.setText(_translate("SOSimMainWindow", "Calibrate", None))
        self.RunButton.setText(_translate("SOSimMainWindow", "Calibrate+Run", None))
        self.RecalcButton.setText(_translate("SOSimMainWindow", "Recalculate", None))
        self.TimeViewGroup.setTitle(_translate("SOSimMainWindow", "TIME VIEW", None))
        self.NextTimeButton.setText(_translate("SOSimMainWindow", ">>", None))
        self.PreviousTimeButton.setText(_translate("SOSimMainWindow", "<<", None))
        self.PanGroup.setTitle(_translate("SOSimMainWindow", "PAN VIEW", None))
        self.PanE.setText(_translate("SOSimMainWindow", "E", None))
        self.PanN.setText(_translate("SOSimMainWindow", "N", None))
        self.PanS.setText(_translate("SOSimMainWindow", " S", None))
        self.PanW.setText(_translate("SOSimMainWindow", "W", None))
        self.GlobalGroup.setTitle(_translate("SOSimMainWindow", "GLOBAL AREA", None))
        self.ProgressLabel.setText(_translate("SOSimMainWindow", "    Calculating...", None))
        self.CancelButton.setText(_translate("SOSimMainWindow", "Cancel", None))
        self.groupBox_3.setTitle(_translate("SOSimMainWindow", "LEGEND", None))
        self.groupBox_4.setTitle(_translate("SOSimMainWindow", "COORDINATES", None))
        self.ParameterGroup.setTitle(_translate("SOSimMainWindow", "6.Parameter Range", None))
        self.DefaultParameterButton.setText(_translate("SOSimMainWindow", "Default", None))
        self.UserDefineParameterButton.setText(_translate("SOSimMainWindow", "Define", None))
        self.VXLable.setToolTip(_translate("SOSimMainWindow", "velocity of X direction", None))
        self.VXLable.setText(_translate("SOSimMainWindow", "VX:", None))
        self.VYLabel.setToolTip(_translate("SOSimMainWindow", "velocity of Y direction", None))
        self.VYLabel.setText(_translate("SOSimMainWindow", "VY:", None))
        self.DXLabel.setToolTip(_translate("SOSimMainWindow", "diffusion coefficient of X direction", None))
        self.DXLabel.setText(_translate("SOSimMainWindow", "DX:", None))
        self.DYLabel.setToolTip(_translate("SOSimMainWindow", "diffusion coefficient of Y direction", None))
        self.DYLabel.setText(_translate("SOSimMainWindow", "DY:", None))
        self.vxMinSpinBox.setToolTip(_translate("SOSimMainWindow", "velocity of X direction", None))
        self.vxMaxSpinBox.setToolTip(_translate("SOSimMainWindow", "velocity of X direction", None))
        self.DxMinSpinBox.setToolTip(_translate("SOSimMainWindow", "diffusion coefficient of X direction", None))
        self.DxMaxSpinBox.setToolTip(_translate("SOSimMainWindow", "diffusion coefficient of  direction", None))
        self.vyMinSpinBox.setToolTip(_translate("SOSimMainWindow", "velocity of Y direction", None))
        self.vyMaxSpinBox.setToolTip(_translate("SOSimMainWindow", "velocity of Y direction", None))
        self.DyMinSpinBox.setToolTip(_translate("SOSimMainWindow", "diffusion coefficient of Y direction", None))
        self.DyMaxSpinBox.setToolTip(_translate("SOSimMainWindow", "diffusion coefficient of Y direction", None))
        self.VXLable_4.setToolTip(_translate("SOSimMainWindow", "velocity of X direction", None))
        self.VXLable_4.setText(_translate("SOSimMainWindow", "Level of Confidence:", None))
        self.vyMinSpinBox_3.setToolTip(_translate("SOSimMainWindow", "Level of Confidence", None))
        self.Outputoptions.setTitle(_translate("SOSimMainWindow", "7.Output Options", None))
        self.CoordinateButton.setText(_translate("SOSimMainWindow", "Coordinate", None))
        self.KmButton.setText(_translate("SOSimMainWindow", "Km", None))
        self.ContourButton.setText(_translate("SOSimMainWindow", "Contour", None))
        self.NocontourButton.setText(_translate("SOSimMainWindow", "No contour", None))
        self.FielddataButton.setText(_translate("SOSimMainWindow", "Field data", None))
        self.NoFielddataButton.setText(_translate("SOSimMainWindow", "No field data", None))
        self.ParameterGroup_3.setTitle(_translate("SOSimMainWindow", "5.Uncertainty Estimates", None))
        self.DefaultParameterButton_6.setText(_translate("SOSimMainWindow", "Best Guess", None))
        self.DefaultParameterButton_7.setText(_translate("SOSimMainWindow", "Minimum Regret:", None))
        self.VXLable_5.setText(_translate("SOSimMainWindow", "Threshold Concentration", None))
        self.DefaultParameterButton_17.setText(_translate("SOSimMainWindow", "0.1%", None))
        self.DefaultParameterButton_18.setText(_translate("SOSimMainWindow", "1%", None))
        self.DefaultParameterButton_19.setText(_translate("SOSimMainWindow", "10%", None))                                          
        #output options group end      
        self.menu_File.setTitle(_translate("SOSimMainWindow", "&File", None))
        self.menuPrint.setTitle(_translate("SOSimMainWindow", "Print...", None))
        self.menuOpen.setTitle(_translate("SOSimMainWindow", "Open...", None))
        self.menuMap.setTitle(_translate("SOSimMainWindow", "Map", None))
        self.menuOptions.setTitle(_translate("SOSimMainWindow", "Options", None))
        self.actionOpen.setText(_translate("SOSimMainWindow", "Open...", None))
        self.actionSave.setText(_translate("SOSimMainWindow", "Save", None))
        self.actionSave_As.setText(_translate("SOSimMainWindow", "Save As...", None))
        self.actionSave_Image.setText(_translate("SOSimMainWindow", "Save Image...", None))
        self.actionQuit.setText(_translate("SOSimMainWindow", "Quit", None))
        self.actionCurrent_Image.setText(_translate("SOSimMainWindow", "Current Image", None))
        self.actionSpill.setText(_translate("SOSimMainWindow", "Spill", None))
        self.actionModeling_area_within_current_spill.setText(_translate("SOSimMainWindow", "Modeling Area of Current Spill", None))
        self.actionAddLayer.setText(_translate("SOSimMainWindow", "Add Raster Layer", None))
        self.actionZoomIn.setText(_translate("SOSimMainWindow", "Zoom In", None))
        self.actionZoomOut.setText(_translate("SOSimMainWindow", "ZoomOut", None))
        self.actionPan.setText(_translate("SOSimMainWindow", "Pan", None))
        self.actionNew.setText(_translate("SOSimMainWindow", "New", None))
        self.actionSelectBoundary.setText(_translate("SOSimMainWindow", "Select Boundary", None))
        self.actionCaptureCoordinates.setText(_translate("SOSimMainWindow", "Capture Coordinates", None))
        self.actionSave_Calibration_As.setText(_translate("SOSimMainWindow", "Save Calibration As...", None))
        self.actionExisting_Output_Image.setText(_translate("SOSimMainWindow", "Existing Output Image", None))
        self.actionDefaultSettings.setText(_translate("SOSimMainWindow", "Default Settings...", None))
        self.actionDefaultGridNodes.setText(_translate("SOSimMainWindow", "Default Grid Nodes...", None))
        self.actionDefaultResolution.setText(_translate("SOSimMainWindow", "Default Resolution...", None))



if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    SOSimMainWindow = QtGui.QMainWindow()
    ui = Ui_SOSimMainWindow()
    ui.setupUi(SOSimMainWindow)
    SOSimMainWindow.show()
    sys.exit(app.exec_())

