# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Python25\Lib\site-packages\PyQt4\MyGUIs\myDialog.ui'
#
# Created: Wed Aug 18 17:38:58 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MyDialog(object):
    def setupUi(self, MyDialog):
        MyDialog.setObjectName("MyDialog")
        MyDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        MyDialog.resize(523, 405)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../Program Files/SOSim/Icons/SOMangel_Icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MyDialog.setWindowIcon(icon)
        self.Options = QtGui.QTabWidget(MyDialog)
        self.Options.setGeometry(QtCore.QRect(10, 10, 501, 311))
        self.Options.setObjectName("Options")
        self.paramsTab = QtGui.QWidget()
        self.paramsTab.setObjectName("paramsTab")
        self.label = QtGui.QLabel(self.paramsTab)
        self.label.setGeometry(QtCore.QRect(20, 20, 471, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.paramsTab)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 211, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.paramsTab)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 211, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.paramsTab)
        self.label_4.setGeometry(QtCore.QRect(320, 50, 46, 14))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.paramsTab)
        self.label_5.setGeometry(QtCore.QRect(410, 50, 46, 14))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.paramsTab)
        self.label_6.setGeometry(QtCore.QRect(20, 140, 241, 16))
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.paramsTab)
        self.label_7.setGeometry(QtCore.QRect(20, 170, 241, 16))
        self.label_7.setObjectName("label_7")
        self.GammaMinFix = QtGui.QLineEdit(self.paramsTab)
        self.GammaMinFix.setGeometry(QtCore.QRect(310, 230, 71, 20))
        self.GammaMinFix.setReadOnly(True)
        self.GammaMinFix.setObjectName("GammaMinFix")
        self.label_8 = QtGui.QLabel(self.paramsTab)
        self.label_8.setGeometry(QtCore.QRect(20, 200, 281, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.paramsTab)
        self.label_9.setGeometry(QtCore.QRect(20, 230, 221, 16))
        self.label_9.setObjectName("label_9")
        self.GammaMaxFix = QtGui.QLineEdit(self.paramsTab)
        self.GammaMaxFix.setGeometry(QtCore.QRect(400, 230, 71, 20))
        self.GammaMaxFix.setReadOnly(True)
        self.GammaMaxFix.setObjectName("GammaMaxFix")
        self.vxMaxSpinBox = QtGui.QDoubleSpinBox(self.paramsTab)
        self.vxMaxSpinBox.setGeometry(QtCore.QRect(400, 80, 71, 22))
        self.vxMaxSpinBox.setMinimum(-99.99)
        self.vxMaxSpinBox.setObjectName("vxMaxSpinBox")
        self.vyMaxSpinBox = QtGui.QDoubleSpinBox(self.paramsTab)
        self.vyMaxSpinBox.setGeometry(QtCore.QRect(400, 110, 71, 22))
        self.vyMaxSpinBox.setMinimum(-99.99)
        self.vyMaxSpinBox.setObjectName("vyMaxSpinBox")
        self.vyMinSpinBox = QtGui.QDoubleSpinBox(self.paramsTab)
        self.vyMinSpinBox.setGeometry(QtCore.QRect(310, 110, 71, 22))
        self.vyMinSpinBox.setMinimum(-99.99)
        self.vyMinSpinBox.setObjectName("vyMinSpinBox")
        self.DxMinSpinBox = QtGui.QDoubleSpinBox(self.paramsTab)
        self.DxMinSpinBox.setGeometry(QtCore.QRect(310, 140, 71, 22))
        self.DxMinSpinBox.setMinimum(0.01)
        self.DxMinSpinBox.setObjectName("DxMinSpinBox")
        self.DxMaxSpinBox = QtGui.QDoubleSpinBox(self.paramsTab)
        self.DxMaxSpinBox.setGeometry(QtCore.QRect(400, 140, 71, 22))
        self.DxMaxSpinBox.setMinimum(0.01)
        self.DxMaxSpinBox.setObjectName("DxMaxSpinBox")
        self.DyMinSpinBox = QtGui.QDoubleSpinBox(self.paramsTab)
        self.DyMinSpinBox.setGeometry(QtCore.QRect(310, 170, 71, 22))
        self.DyMinSpinBox.setMinimum(0.01)
        self.DyMinSpinBox.setObjectName("DyMinSpinBox")
        self.DyMaxSpinBox = QtGui.QDoubleSpinBox(self.paramsTab)
        self.DyMaxSpinBox.setGeometry(QtCore.QRect(400, 170, 71, 22))
        self.DyMaxSpinBox.setMinimum(0.01)
        self.DyMaxSpinBox.setObjectName("DyMaxSpinBox")
        self.roMinSpinBox = QtGui.QDoubleSpinBox(self.paramsTab)
        self.roMinSpinBox.setGeometry(QtCore.QRect(310, 200, 71, 22))
        self.roMinSpinBox.setMinimum(-0.99)
        self.roMinSpinBox.setMaximum(0.99)
        self.roMinSpinBox.setObjectName("roMinSpinBox")
        self.roMaxSpinBox = QtGui.QDoubleSpinBox(self.paramsTab)
        self.roMaxSpinBox.setGeometry(QtCore.QRect(400, 200, 71, 22))
        self.roMaxSpinBox.setObjectName("roMaxSpinBox")
        self.vxMinSpinBox = QtGui.QDoubleSpinBox(self.paramsTab)
        self.vxMinSpinBox.setGeometry(QtCore.QRect(310, 80, 71, 22))
        self.vxMinSpinBox.setMinimum(-99.99)
        self.vxMinSpinBox.setObjectName("vxMinSpinBox")
        self.Options.addTab(self.paramsTab, "")
        self.gridTab = QtGui.QWidget()
        self.gridTab.setObjectName("gridTab")
        self.label_10 = QtGui.QLabel(self.gridTab)
        self.label_10.setGeometry(QtCore.QRect(30, 20, 441, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtGui.QLabel(self.gridTab)
        self.label_11.setGeometry(QtCore.QRect(30, 71, 111, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtGui.QLabel(self.gridTab)
        self.label_12.setGeometry(QtCore.QRect(30, 110, 101, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtGui.QLabel(self.gridTab)
        self.label_13.setGeometry(QtCore.QRect(30, 170, 441, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtGui.QLabel(self.gridTab)
        self.label_14.setGeometry(QtCore.QRect(90, 190, 381, 16))
        self.label_14.setObjectName("label_14")
        self.EWdefault = QtGui.QSpinBox(self.gridTab)
        self.EWdefault.setGeometry(QtCore.QRect(150, 70, 71, 22))
        self.EWdefault.setObjectName("EWdefault")
        self.NSdefault = QtGui.QSpinBox(self.gridTab)
        self.NSdefault.setGeometry(QtCore.QRect(150, 110, 71, 22))
        self.NSdefault.setObjectName("NSdefault")
        self.Options.addTab(self.gridTab, "")
        self.resolutionTab = QtGui.QWidget()
        self.resolutionTab.setObjectName("resolutionTab")
        self.label_15 = QtGui.QLabel(self.resolutionTab)
        self.label_15.setGeometry(QtCore.QRect(30, 20, 431, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtGui.QLabel(self.resolutionTab)
        self.label_16.setGeometry(QtCore.QRect(30, 100, 431, 16))
        self.label_16.setObjectName("label_16")
        self.label_19 = QtGui.QLabel(self.resolutionTab)
        self.label_19.setGeometry(QtCore.QRect(30, 140, 261, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtGui.QLabel(self.resolutionTab)
        self.label_20.setGeometry(QtCore.QRect(390, 140, 46, 14))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtGui.QLabel(self.resolutionTab)
        self.label_21.setGeometry(QtCore.QRect(30, 40, 431, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtGui.QLabel(self.resolutionTab)
        self.label_22.setGeometry(QtCore.QRect(30, 60, 411, 16))
        self.label_22.setObjectName("label_22")
        self.resolutionMax = QtGui.QDoubleSpinBox(self.resolutionTab)
        self.resolutionMax.setGeometry(QtCore.QRect(300, 140, 81, 22))
        self.resolutionMax.setObjectName("resolutionMax")
        self.Options.addTab(self.resolutionTab, "")
        self.ApplyButton = QtGui.QPushButton(MyDialog)
        self.ApplyButton.setGeometry(QtCore.QRect(270, 350, 81, 25))
        self.ApplyButton.setObjectName("ApplyButton")
        self.RestoreButton = QtGui.QPushButton(MyDialog)
        self.RestoreButton.setGeometry(QtCore.QRect(90, 350, 161, 25))
        self.RestoreButton.setObjectName("RestoreButton")
        self.CancelButton = QtGui.QPushButton(MyDialog)
        self.CancelButton.setGeometry(QtCore.QRect(370, 350, 81, 25))
        self.CancelButton.setObjectName("CancelButton")

        self.retranslateUi(MyDialog)
        self.Options.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MyDialog)

    def retranslateUi(self, MyDialog):
        MyDialog.setWindowTitle(QtGui.QApplication.translate("MyDialog", "Modify Default Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MyDialog", "SOSim uses the following default parameters ranges as the full set of physically possible values:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MyDialog", "Advective velocity in the x direction (km/d):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MyDialog", "Advective velocity in the y direction (km/d):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MyDialog", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MyDialog", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MyDialog", "Coefficient of Diffusion in the x direction (km2/d):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MyDialog", "Coefficient of Diffusion in the y direction (km2/d):", None, QtGui.QApplication.UnicodeUTF8))
        self.GammaMinFix.setText(QtGui.QApplication.translate("MyDialog", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MyDialog", "Coefficient of Correlation between x and y directions [-]:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MyDialog", "Weighting Parameters (fixed %):", None, QtGui.QApplication.UnicodeUTF8))
        self.GammaMaxFix.setText(QtGui.QApplication.translate("MyDialog", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.Options.setTabText(self.Options.indexOf(self.paramsTab), QtGui.QApplication.translate("MyDialog", "Parameters Range", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MyDialog", "SOSim conforms the modeling grid using the following default number of nodes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MyDialog", "East-West (E-W):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MyDialog", "North-South (N-S):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MyDialog", "WARNING:   modeling run time may substantially increase with the number of", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MyDialog", " grid nodes depending on the machine\'s processing power", None, QtGui.QApplication.UnicodeUTF8))
        self.Options.setTabText(self.Options.indexOf(self.gridTab), QtGui.QApplication.translate("MyDialog", "Grid nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MyDialog", "SOSim sets the resolution of the modeling region based on the lenght/nodes ratio, and ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MyDialog", "Allow for: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MyDialog", "Maximum (constant) separation between grid nodes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MyDialog", "km", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MyDialog", "displays warning messages when user input needs corrective measures to comply with ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MyDialog", "optimum resolution requirements.", None, QtGui.QApplication.UnicodeUTF8))
        self.Options.setTabText(self.Options.indexOf(self.resolutionTab), QtGui.QApplication.translate("MyDialog", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.ApplyButton.setText(QtGui.QApplication.translate("MyDialog", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.RestoreButton.setText(QtGui.QApplication.translate("MyDialog", "Restore Default Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.CancelButton.setText(QtGui.QApplication.translate("MyDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

